services:
  clickhouse:
    container_name: clickhouse
    build: .
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE__DATABASE}
      CLICKHOUSE_USER: ${CLICKHOUSE__CONNECTION__USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE__CONNECTION__PASSWORD}
    ports:
      - ${CLICKHOUSE__CONNECTION__HTTP_PORT}:8123
      - ${CLICKHOUSE__CONNECTION__TCP_PORT}:9000
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
